# Generated by Django 4.1.7 on 2023-02-28 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_littlenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mualliflarnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('fakultetnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('kafedranomi', models.TextField(blank=True, max_length=500, null=True)),
                ('nomi', models.TextField(blank=True, max_length=500, null=True)),
                ('Raqami', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
