# Generated by Django 4.1.7 on 2023-02-28 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_dgu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mualliflarnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('fakultetnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('kafedranomi', models.TextField(blank=True, max_length=500, null=True)),
                ('nomi', models.TextField(blank=True, max_length=500, null=True)),
                ('Raqami', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MualliflikHuquqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mualliflarnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('fakultetnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('kafedranomi', models.TextField(blank=True, max_length=500, null=True)),
                ('nomi', models.TextField(blank=True, max_length=500, null=True)),
                ('Raqami', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname', models.TextField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mualliflarnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('fakultetnomi', models.TextField(blank=True, max_length=500, null=True)),
                ('kafedranomi', models.TextField(blank=True, max_length=500, null=True)),
                ('nomi', models.TextField(blank=True, max_length=500, null=True)),
                ('Raqami', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
