# Generated by Django 4.1.7 on 2023-03-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_bgu_mualliflikhuquqi_news_patent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LittleNews',
        ),
    ]
